//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErVe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORM
    {
        public int FormID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string FormFiller { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerContact { get; set; }
        public Nullable<int> WorkID { get; set; }
        public string WorkName { get; set; }
        public Nullable<System.DateTime> ReadyToDate { get; set; }
        public string Instructions { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> PcsAmount { get; set; }
        public Nullable<decimal> ChargeFull { get; set; }
        public Nullable<decimal> ChargeByPcs { get; set; }
        public Nullable<decimal> FreightCost { get; set; }
        public Nullable<int> MaterialID { get; set; }
        public string MaterialName { get; set; }
        public Nullable<int> WorkHoursWR { get; set; }
        public Nullable<int> WorkHoursIT { get; set; }
        public Nullable<int> WorkHoursCS { get; set; }
        public Nullable<int> StatusID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Material Material { get; set; }
        public virtual Status Status { get; set; }
        public virtual Work Work { get; set; }
    }
}
