//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ErveEntitiesdb01 : DbContext
    {
        public ErveEntitiesdb01()
            : base("name=ErveEntitiesdb01")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<FORM> FORM { get; set; }
        public virtual DbSet<Material> Material { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Testi2> Testi2 { get; set; }
        public virtual DbSet<Work> Work { get; set; }
    }
}
